backend:
  name: github
  repo: luizfverissimo/dms-ecommerce
  branch: main
  site_domain: darwinmusicstore.netlify.app
media_folder: public/static/img
media_library:
  name: cloudinary
  config:
    cloud_name: dqhq5frtg
    api_key: 598489975237945
site_url: darwinmusicstore.netlify.app
display_url: https://darwinmusicstore.netlify.app
logo_url: https://darwinmusicstore.netlify.app/logo-dark-text.svg
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - label: 'Produtos'
    name: 'products'
    folder: 'content/products'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Título', name: 'title', widget: 'string', required: true }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["Pedais", "Instrumentos", "Outros"], required: true }
      - { label: 'Lançamento', name: 'isLaunch', widget: 'boolean', default: true, required: true }
      - { label: 'Preço', name: 'price', widget: 'number', value_type: "float", default: 0.00, min: 0,  required: true }
      - { label: 'Texto do preço', name: 'priceText', widget: 'string', required: false }
      - {
          label: 'Foto da capa',
          name: 'coverImage',
          widget: 'image',
          required: true,
          allow_multiple: false
        }
      - {
          label: 'Fotos',
          name: 'images',
          widget: 'image',
          required: true,
          media_library:
            config:
              multiple: true     
        }
      - { label: 'Vídeo', name: 'video', widget: 'string', required: false}
      - { label: 'Descrição', name: 'body', widget: 'markdown', required: true }
