backend:
  name: github
  repo: luizfverissimo/birds-of-brazil-portfolio
  branch: main
  site_domain: lcverissimo.netlify.app
media_folder: /static/img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - label: 'Produtos'
    name: 'products'
    folder: 'content/products'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Título', name: 'title', widget: 'string', required: true }
      - { label: 'Categoria', name: 'category', widget: 'select', options: ["Pedais", "instrumentos, "Outros"], required: true }
      - { label: 'Lançamento', name: 'isLaunch', widget: 'boolean', default: true, required: true }
      - { label: 'Preço', name: 'price', widget: 'number', value_type: "float", default: 0.00, min: 0,  required: true }
      - { label: 'Texto do preço', name: 'priceText', widget: 'string', required: false }
      - {
          label: 'Foto da capa',
          name: 'coverImage',
          widget: 'image',
          required: true,
          allow_multiple: false
        }
      - {
          label: 'Fotos',
          name: 'image',
          widget: 'image',
          required: true,
          allow_multiple: true
        }
      - { label: 'Vídeo', name: 'video', widget: 'string', required: false}
      - { label: 'Descrição', name: 'body', widget: 'markdown', required: true }
